### ISSUE TITLE
version 2.2.6 do not support mekanica (mekanism)

### ISSUE THREAD

**Issue by collwee** [TagnumElite/ProjectE-Integration#9]
**Describe the bug**
mekanica is a build of mekanism that is way more updated and have better performance

it ask specifically for mekanica 1.12.2-9.6.7.360 or above (you have 1.12.2-1.2.0b3)

https://minecraft.curseforge.com/projects/mekanica

**Comment by TagnumElite** [comment]
Try 2.2.7, I disabled the required version check.

**Comment by collwee** [comment]
the game lunch but when i try to enter a world it crash

https://pastebin.com/z3a765ET

**Comment by collwee** [comment]
the game lunch but when i try to enter a world it crash
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ProjectE Integration (projecteintegration)
Caused by: java.lang.NoSuchMethodError: mekanism.common.recipe.RecipeHandler$Recipe.get()Ljava/util/Map;
    at com.tagnumelite.projecteintegration.plugins.PluginMekanism$BasicMachineMapper.setup(PluginMekanism.java:171)
    at com.tagnumelite.projecteintegration.PEIntegration.serverAboutToStart(PEIntegration.java:135)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:854)
    at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:155)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)

**Comment by TagnumElite** [comment]
I have discovered the problem, Mekanica returns an HashMap for the recipes, Mekanism returns an ordinary Map

**Comment by TagnumElite** [comment]
I don't see any way to fix this, I am going to see if I can get the Mekanica developers to add or change their one function.

**Comment by TagnumElite** [comment]
Fixed in 2.2.9

**Comment by cemolewup** [comment]
The problem still exists in 2.2.10. Disabling Mekanica to let projecte integrations generate it's config, then disabling the Mekanism part doesn't fix it either, since it won't let you launch the game.

**Comment by TagnumElite** [comment]
Mekanica has been merged into mekanism 9.7, ProjectE 2.2.10 supports that mekanism version and above

**Comment by TagnumElite** [comment]
2.2.11 now supports mekanica version as well
